/*
 * Here comes the text of your license
 * Each line should be prefixed with  * 
 */
package XiaoLineScan;

import ij.ImagePlus;
import ij.gui.Overlay;
import ij.gui.Roi;
import ij.gui.StackWindow;
import java.awt.event.WindowEvent;
import java.util.HashMap;
import javax.swing.DefaultListModel;

/**
 *
 * @author Mutt
 */
public class RoiListManager extends javax.swing.JFrame {

    private final HashMap<String, Roi> roiMap = new HashMap<>();
    private final ImagePlus imp;
    private final StackWindow imageWd;
    private final Overlay ovl;
    private final DefaultListModel<String> listModel = new DefaultListModel<>();
    private int editingIndex = -1;

    /**
     * Creates new form RoiListManager
     *
     * @param imagePlus
     * @param imageWindow
     */
    public RoiListManager(ImagePlus imagePlus, StackWindow imageWindow) {
        initComponents();
        imp = imagePlus;
        imageWd=imageWindow;
        if (imp.getOverlay() != null) {
            ovl = imp.getOverlay();
        } else {
            ovl = new Overlay();
        }
        loadRoiToDisplayList();
    }

    private void loadRoiToDisplayList() {
        int i = 0;
        for (Roi roi : ovl.toArray()) {
            String name = Integer.toString(i) + "-" + roi.getHashCode();
            roiMap.put(name, roi);
            listModel.addElement(name);
            i++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        roiDisplayList = new javax.swing.JList<>();
        deleteBn = new javax.swing.JButton();
        addBn = new javax.swing.JButton();
        doneBn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ROI Manager");
        setAlwaysOnTop(true);
        setResizable(false);

        roiDisplayList.setModel(listModel);
        roiDisplayList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roiDisplayListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(roiDisplayList);

        deleteBn.setText("Delete");
        deleteBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBnActionPerformed(evt);
            }
        });

        addBn.setText("Add");
        addBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBnActionPerformed(evt);
            }
        });

        doneBn.setText("Done");
        doneBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneBnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteBn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addBn, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(doneBn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deleteBn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addBn, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(doneBn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roiDisplayListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roiDisplayListMouseClicked

        if (editingIndex != -1) {
            addBn.setText("Add");
            String name = listModel.getElementAt(editingIndex);
            Roi roi = imp.getRoi();
            roiMap.replace(name, roi);
            ovl.add(roi);
            editingIndex=-1;
            imp.deleteRoi();

        }
        if (evt.getClickCount() == 2) {
            addBn.setText("Accept");
            editingIndex = roiDisplayList.locationToIndex(evt.getPoint());
            String name = listModel.get(editingIndex);
            Roi roi = roiMap.get(name);
            imp.setRoi(roi, true);
            ovl.remove(roi);

        }

        imp.setOverlay(ovl);

    }//GEN-LAST:event_roiDisplayListMouseClicked

    private void deleteBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBnActionPerformed
        int[] selected = roiDisplayList.getSelectedIndices();
        for (int i : selected) {
            String name = listModel.get(i);
            listModel.remove(i);
            Roi roi = roiMap.remove(name);
            ovl.remove(roi);

            if (editingIndex != -1) {
                editingIndex = -1;
                addBn.setText("Add");
            }

        }
        imp.deleteRoi();
        imp.setOverlay(ovl);
    }//GEN-LAST:event_deleteBnActionPerformed

    private void addBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBnActionPerformed
        Roi roi = imp.getRoi();
        if (roi != null) {
            if (editingIndex != -1) {
                String name = listModel.getElementAt(editingIndex);
                roiMap.replace(name, roi);
                editingIndex = -1;
                addBn.setText("Add");
            } else {
                String name = listModel.size() + "-" + roi.getHashCode();
                listModel.addElement(name);
                //roiDisplayList.setModel(listModel);
                roiMap.put(name, roi);
            }
            ovl.add(roi);
            imp.deleteRoi();
            imp.setOverlay(ovl);
        }
    }//GEN-LAST:event_addBnActionPerformed

    private void doneBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneBnActionPerformed
        imageWd.dispatchEvent(new WindowEvent(imageWd, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_doneBnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBn;
    private javax.swing.JButton deleteBn;
    private javax.swing.JButton doneBn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> roiDisplayList;
    // End of variables declaration//GEN-END:variables
}
